name: node-ci-deployment

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Récupère le contenu du dépôt correspondant au commit du workflow en cours
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Commande pour exécuter les tests

      - name: Linting with ESLint
        run: npm run lint